### ISSUE TITLE
Error on 2022-05-23

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/tilelog#10]
```
Generating files for 2022-05-23
Traceback (most recent call last):
  File "/srv/pnorman/osm/tilelog/venv/bin/tilelog", line 11, in <module>
    load_entry_point('tilelog', 'console_scripts', 'tilelog')()
  File "/srv/pnorman/osm/tilelog/venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/srv/pnorman/osm/tilelog/venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/srv/pnorman/osm/tilelog/venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/srv/pnorman/osm/tilelog/venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/srv/pnorman/osm/tilelog/tilelog/__init__.py", line 51, in cli
    tilelog.location.create_location(curs, date)
  File "/srv/pnorman/osm/tilelog/tilelog/location.py", line 49, in create_location
    curs.execute(insert_query,
  File "/srv/pnorman/osm/tilelog/venv/lib/python3.9/site-packages/pyathena/util.py", line 37, in _wrapper
    return wrapped(*args, **kwargs)
  File "/srv/pnorman/osm/tilelog/venv/lib/python3.9/site-packages/pyathena/arrow/cursor.py", line 153, in execute
    raise OperationalError(query_execution.state_change_reason)
pyathena.error.OperationalError: Query exhausted resources at this scale factor. If a data manifest file was generated at 's3://openstreetmap-fastly-processed-logs/tilelogs/3d1975d2-c82a-41b7-8537-6a57c5e7ab1e-manifest.csv', you may need to manually clean the data from locations specified in the manifest. Athena will not delete data in your account.
```

**Comment by pnorman** [comment]
It worked fine when I retried. There's a couple possibilities.

- it was a transient error, and can't be reproduced. -> dead end
- running queries in parallel exhausted resources. -> only an issue during backfill, where I have multiple days generating at once
