### ISSUE TITLE
Failure on 2023-08-29

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/tilelog#11]
```
Aug 30 01:07:00 norbert.openstreetmap.org systemd[1]: Started Tile log analysis.
Aug 30 01:07:01 norbert.openstreetmap.org tilelog[1672496]: Generating files for 2023-08-29
Aug 30 01:50:48 norbert.openstreetmap.org tilelog[1672496]: Querying for tile usage
Aug 30 01:56:14 norbert.openstreetmap.org tilelog[1672496]: Traceback (most recent call last):
Aug 30 01:56:14 norbert.openstreetmap.org tilelog[1672496]:   File "/opt/tilelog/bin/tilelog", line 8, in <module>
Aug 30 01:56:14 norbert.openstreetmap.org tilelog[1672496]:     sys.exit(cli())
Aug 30 01:56:14 norbert.openstreetmap.org tilelog[1672496]:   File "/opt/tilelog/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
Aug 30 01:56:14 norbert.openstreetmap.org tilelog[1672496]:     return self.main(*args, **kwargs)
Aug 30 01:56:14 norbert.openstreetmap.org tilelog[1672496]:   File "/opt/tilelog/lib/python3.10/site-packages/click/core.py", line 1055, in main
Aug 30 01:56:14 norbert.openstreetmap.org tilelog[1672496]:     rv = self.invoke(ctx)
Aug 30 01:56:14 norbert.openstreetmap.org tilelog[1672496]:   File "/opt/tilelog/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
Aug 30 01:56:14 norbert.openstreetmap.org tilelog[1672496]:     return ctx.invoke(self.callback, **ctx.params)
Aug 30 01:56:14 norbert.openstreetmap.org tilelog[1672496]:   File "/opt/tilelog/lib/python3.10/site-packages/click/core.py", line 760, in invoke
Aug 30 01:56:14 norbert.openstreetmap.org tilelog[1672496]:     return __callback(*args, **kwargs)
Aug 30 01:56:14 norbert.openstreetmap.org tilelog[1672496]:   File "/opt/tilelog/lib/python3.10/site-packages/tilelog/__init__.py", line 54, in cli
Aug 30 01:56:14 norbert.openstreetmap.org tilelog[1672496]:     tile_logs(curs, date, tile)
Aug 30 01:56:14 norbert.openstreetmap.org tilelog[1672496]:   File "/opt/tilelog/lib/python3.10/site-packages/tilelog/__init__.py", line 77, in tile_logs
Aug 30 01:56:14 norbert.openstreetmap.org tilelog[1672496]:     curs.execute(query, {"year": date.year, "month": date.month,
Aug 30 01:56:14 norbert.openstreetmap.org tilelog[1672496]:   File "/opt/tilelog/lib/python3.10/site-packages/pyathena/arrow/cursor.py", line 159, in execute
Aug 30 01:56:14 norbert.openstreetmap.org tilelog[1672496]:     raise OperationalError(query_execution.state_change_reason)
Aug 30 01:56:14 norbert.openstreetmap.org tilelog[1672496]: pyathena.error.OperationalError: Query exhausted resources at this scale factor
Aug 30 01:56:14 norbert.openstreetmap.org systemd[1]: tilelog.service: Main process exited, code=exited, status=1/FAILURE
Aug 30 01:56:14 norbert.openstreetmap.org systemd[1]: tilelog.service: Failed with result 'exit-code'.
Aug 30 01:56:14 norbert.openstreetmap.org systemd[1]: tilelog.service: Consumed 25.562s CPU time.
```

**Comment by pnorman** [comment]
It generated the new aggregated logs fine, so this was in one of the csv or xz files

**Comment by pnorman** [comment]
I made some changes that should help with this in 1.7.0

@tomhughes I've generated the files and they're uploaded at https://pnorman.dev.openstreetmap.org/2023-08-29/

**Comment by tomhughes** [comment]
I've put those logs in place now.
